[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
itertools = "*"
regex = "*"
intervallum = "1.4.0"
gcollections = "1.5.0"
sliding_windows = "3.0"